services:
  postgres:
    image: postgres:16
    container_name: my_app_db
    environment:
      POSTGRES_USER: akhil
      POSTGRES_PASSWORD: test
      POSTGRES_DB: my_app_db
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
